# Generated by Django 4.2.4 on 2023-08-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_institucion_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
