# Generated by Django 4.2.4 on 2023-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_provincia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instimagenes',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
