# Generated by Django 4.2.4 on 2023-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_instimagenes_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instimagenes',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
