# Generated by Django 4.2.4 on 2023-08-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instimagenes_disponible_institucion_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instimagenes',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.institucion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institucion', to='core.municipio'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institucion', to='core.provincia'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='core.provincia'),
        ),
    ]
