# Generated by Django 4.2.4 on 2023-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_municipio_nombre_alter_provincia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
