# Generated by Django 4.2.4 on 2023-08-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_alter_municipio_imagen_alter_provincia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instimagenes',
            name='institucion',
        ),
        migrations.AddField(
            model_name='instimagenes',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instimagenes',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
