# Generated by Django 4.2.4 on 2023-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_instimagenes_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
