# Generated by Django 4.2.4 on 2023-08-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_instimagenes_institucion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instimagenes',
            name='core_instim_content_2c3ac1_idx',
        ),
        migrations.RemoveField(
            model_name='instimagenes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='instimagenes',
            name='object_id',
        ),
    ]
