# Generated by Django 4.2.4 on 2023-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_institucion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='plus_code',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
