# Generated by Django 4.2.4 on 2023-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_institucion_plus_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='plus_code',
            new_name='latitud',
        ),
        migrations.AddField(
            model_name='institucion',
            name='longitud',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
