# Generated by Django 4.2.4 on 2023-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_institucion_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instimagenes',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='instimagenes',
            name='descripcion_en',
            field=models.TextField(default=1, help_text='Descripción de la Imagen en Inglés.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instimagenes',
            name='descripcion_es',
            field=models.TextField(default=1, help_text='Descripción de la Imagen en Español.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='descripcion_en',
            field=models.TextField(default=1, help_text='Descripción de la Institución en Inglés.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='descripcion_es',
            field=models.TextField(default=1, help_text='Descripción de la Institución en Español.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='descripcion_en',
            field=models.TextField(default=1, help_text='Descripción del Municipio en Inglés.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='descripcion_es',
            field=models.TextField(default=1, help_text='Descripción del Municipio en Español.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='descripcion_en',
            field=models.TextField(default=1, help_text='Descripción de la Provincia en Inglés.', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='descripcion_es',
            field=models.TextField(default=1, help_text='Descripción de la Provincia en Español.', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
