# Generated by Django 4.2.4 on 2023-09-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_instimagenes_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstImagenes',
            new_name='Imagenes',
        ),
    ]
