# Generated by Django 4.2.4 on 2023-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tipo_institucion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='urgencia',
            field=models.BooleanField(default=False),
        ),
    ]
